/*
 *   Author: matthew6868(mxu.public@outlook.com)
 *   Date: 2016-11-09
 *
 *   389. Find the Difference   QuestionEditorial Solution  My Submissions
 *   Total Accepted: 34155
 *   Total Submissions: 68560
 *   Difficulty: Easy
 *   Contributors: Admin
 *   Given two strings s and t which consist of only lowercase letters.
 *
 *   String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 *   Find the letter that was added in t.
 *
 *   Example:
 *
 *    Input:
 *   s = "abcd"
 *   t = "abcde"
 *
 *   Output:
 *   e
 *
 *   Explanation:
 *   'e' is the letter that was added.
 */
class Solution {
public:
    char findTheDifference(string s, string t) {
        // save the count in a has table for each char, and compare the difference one.
        std::map<char, int> smap;
        std::map<char, int> tmap;

        for (int i = 0; i < s.size(); ++i) {
            auto it = smap.find(s[i]);
            if (it == smap.end()) {
                smap.insert(std::pair<char, int>(s[i], 1));
            } else {
                it->second++;
            }

        }

        for (int i = 0; i < t.size(); ++i) {
            auto it = tmap.find(t[i]);
            if (it == tmap.end()) {
                tmap.insert(std::pair<char, int>(t[i], 1));
            } else {
                it->second++;
            }
        }

        for (int i =0; i < t.size(); ++i) {
            auto tIt = tmap.find(t[i]);
            auto sIt = smap.find(t[i]);
            if (sIt == smap.end() || sIt->second != tIt->second) {
                return tIt->first;
            }
        }

        return '\0';
    }
};