/*
 *   Author: matthew6868(mxu.public@outlook.com)
 *   Date: 2016-11-09
 *
 *   389. Find the Difference   QuestionEditorial Solution  My Submissions
 *   Total Accepted: 34155
 *   Total Submissions: 68560
 *   Difficulty: Easy
 *   Contributors: Admin
 *   Given two strings s and t which consist of only lowercase letters.
 *
 *   String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 *   Find the letter that was added in t.
 *
 *   Example:
 *
 *    Input:
 *   s = "abcd"
 *   t = "abcde"
 *
 *   Output:
 *   e
 *
 *   Explanation:
 *   'e' is the letter that was added.
 */
public class Solution {
    public char findTheDifference(String s, String t) {
        int i = 0, res = 0;
        
        for (i = 0; i < s.length(); i++) {
            res ^= s.charAt(i) ^ t.charAt(i);
        }
        
        return (char)(res ^ t.charAt(i)); // t[i] is the last element in t
    }
}